### ISSUE TITLE
A "Fork" in the road

### ISSUE THREAD

**Issue by pkl728** [MvvmCross/MvvmCross-SQLite#47] opened 2015-03-27 12:32 UTC
Hey guys,

It appears that we have a number of people still relying on this package for their MvvmCross apps.  As it sounds like https://github.com/praeclarum/sqlite-net/issues/135 is no where near started/completed I think we have a decision that needs to be made.

This package will always be hopelessly behind unless we are able to get our builds onto one of these main repos.

As I see it we have three options:
1.)  Keep this as a separate repo and occasionally update it as we need it (what we are doing now)
2.)  Spec out what needs to happen for https://github.com/praeclarum/sqlite-net/issues/135 to be completed
3.)  Use https://github.com/oysteinkrog/SQLite.Net-PCL

Is 3 ultimately what we are trying to achieve with this package?  It appears @oysteinkrog has SQLite.Net (which was forked from @praeclarum 's project) as a PCL project.  Unless I'm misunderstanding the differences between the two repos?

If that is the case, wouldn't this be as simple as throwing up a -MvvmCross solution on @oysteinkrog's repo which has MvvmCross plugins and then give it it's own nuget package?  That way we could always be up to date with the latest and greatest.

What are other people's thoughts?  @slodge I know you were in talks with @praeclarum at one point about a solution and it sounded like you guys came to an agreement on something but just needed the help to implement it.  Did you have more details on what was required?

As a side note, I've seen a couple people mention that they have successfully ditched MvvmCross-Community for https://github.com/oysteinkrog/SQLite.Net-PCL...

**Comment by praeclarum** [comment] 2015-03-27 16:44
Part of the reason I don’t do the work is I don’t understand what you need. Why don’t you just use the official PCL version? https://www.nuget.org/packages/sqlite-net-pcl/ <https://www.nuget.org/packages/sqlite-net-pcl/> 

I don’t know anything about @oysteinkrog’s project other than he took my name. :-)

That issue requested splitting the library into 2 files. That’s not going to happen.

We discussed adding an interface to the connection class. I don’t like pointless abstraction so that’s why that hasn’t happened. AFAIK you guys have your own interface over SQLite - what’s wrong with that?

Sorry but I don’t use MvvmCross and don’t know why you’re having such problems. Just add sqlite-net and compile it into your stuffs. But I guess that’s why you want two files? To simplify your build process? Just make a master tracking fork with that 1 line change - it will rarely conflict.

-Frank

**Comment by oysteinkrog** [comment] 2015-03-27 16:47
Hi @praeclarum, I'm sorry if you feel I stole the name, it was never my intention to steal anything, I just wanted to make a PCL version, with a different philosophy with regards to code organization etc.

**Comment by pkl728** [comment] 2015-03-27 18:45
@praeclarum I'm sorry if you took this issue to mean you needed to do anything specifically.  I only included your name on here as it sounded like you and @slodge had discussed some kind of solution at some point.

Basically I'm trying to get down to the bottom of whether or not this package even needs to exist since it sounds like there are viable PCL packages we could use.  This project was first started before PCL's were reliable so now I'm just asking the question... Do we need this?

My intent of this issue was for us, the people using the MvvmCross Community SQLite package, to decide the best course of action.

To me this project seems redundant if we can just use a PCL to make this happen.  I think, and correct me if I'm wrong here @slodge, we just need to create some MvvmCross plugins that pull in the appropriate PCL packages.

Perhaps we could roll this back into the main MvvmCross package and simply wrap a plugin around either of these projects?  I highly doubt we are going to need any changes to SQLite under the hood that wouldn't already be done on one of these other projects and if we do we could be helpful and contribute back to the community as a whole.

Thoughts?

**Comment by slodge** [comment] 2015-03-29 17:46
Hi @praeclarum I'm sorry if the wind hasn't been good for sailing yet this year - but hope you get some more in soon :)

-----

(Ahem... sorry... just wanted to join in the "Hi @praeclarum I'm sorry" club :))

-----

Back to the issue... I'm not sure this is an easy issue to discuss here....

-----

I completely agree the world has moved on in a good way from when we first created this PCL wrapper for SQLite-Net - now the world **loves** PCL.

I also have yet to see "the community" take on the task of maintaining this SQLite-net repo across all platforms. We've done really well on iOS and Android - but seems like no-one has enough time for poor old Windows (and new Windows)...

I suggest we close this issue... let's move the discussion back to #39

**Closed by slodge** 2015-03-29 17:46 UTC

**Comment by j-hayes** [comment] 2015-03-30 02:17
I know this issue is closed, but I can confirm that  @oysteinkrog's version works in my SQLite driven app. I just ported mine to use this. And it does work on Windows Phone and Store (which was my main issue with the current state of this repo.)
